server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/www_data_btlon
    username: root
    password: sapassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5